version: 2

sources:
  - name: raw_data
    description: "Raw data dumps from various systems"
    database: "{{ var('project_name') }}"
    schema: "DEV_raw"
    tables:
      - name: raw_policies
        description: "policies"
      - name: raw_claims
        description: '{{ doc("stg_table_docs") }}'
      - name: raw_policyholders
        description: "raw policy holders upload"
      - name: raw_incremental
        description: "Source for the incremental model"